name: Go

on:
  pull_request:
    branches: [ master ]
    
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Test Assignment 1-1
      run: | 
        cd assignment1-1
        go mod init cos418_hw1_1
        go mod tidy
        go test -v
    
    - name: Test Assignment 1-2 (1)
      run: | 
        cd assignment1-2/src/mapreduce
        go mod init mapreduce
        go mod tidy
        go test -v -run Sequential
    
    - name: Test Assignment 1-2 (2)
      run: | 
        ln -s $PWD/assignment1-2/src/mapreduce $GOROOT/src/mapreduce 
        cd assignment1-2/src/main
        sh ./test-wc.sh
    
    - name: Test Assignment 1-3 (1 & 2)
      run: | 
        cd assignment1-3/src/mapreduce
        go mod init mapreduce
        go mod tidy
        sudo go test -v -run TestBasic
        sudo go test -v -run Failure
    
    - name: Test Assignment 1-2 (3)
      run: | 
        ln -s $PWD/assignment1-3/src/mapreduce $GOROOT/src/mapreduce 
        cd assignment1-3/src/main
        sh ./test-ii.sh

    - name: Test Assignment 2
      run: | 
        cd assignment2/src/chandy-lamport
        go mod init chandy_lamport
        go mod tidy
        go test

    - name: Test Assignment 3-1 (elections)
      run: | 
        cd assignment3-1
        go mod init main
        go mod tidy
        go test -run InitialElection
        go test -run ReElection