name: Go

on:
  pull_request:
    branches: [ master ]
  push: 
    branches: [ assignment1-workflow ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Test Assignment 1-1
      run: cd assignment1-1 | export GO111MODULE=auto | go test
