name: Go

on:
  pull_request:
    branches: [ master ]
  push: 
    branches: [ assignment1-workflow ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Test Assignment 1-1
      run: | 
        cd assignment1-1
        go mod init cos418_hw1_1
        go mod tidy
        go test
    
    - name: Test Assignment 1-2
      run: | 
        cd assignment1-2/src/mapreduce
        go mod init mapreduce
        go mod tidy
        go test -v -run Sequential
        sh ./test-wc.sh
